<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<meta name="author" content="merk">

	<title><?= $this->e($title) ?></title>
	<link rel="stylesheet" href="/assets/css/bootstrap.min.css">
	<link rel="stylesheet" href="/assets/css/tether.min.css">
	<script src="/assets/js/jquery-3.2.1.min.js"></script>
	<script src="/assets/js/tether.min.js"></script>
	<script src="/assets/js/bootstrap.min.js"></script>
	<?= $this->section('head-src') ?>
</head>
<body>
<div class="container">
	<?= $this->section('content') ?>
</div>
<script src="<?= $this->asset('/assets/js/app.js') ?>"></script>

</body>
<?= $this->section('footer-src') ?>
</html>