<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="author" content="merk">
    <link rel="stylesheet" href="/assets/css/bootstrap.min.css">
    <title>404 - Not Found</title>
</head>
<body>
<div class="container" style="margin: auto">
    <div class="mt-1">
        <h1 class="text-info">404 - Not found</h1>
    </div>
    <p class="lead">Запрашиваемая страница не найдена на сервере.</p>
    Вы можете вернуться
    <a onclick="history.back(-1)" href="#"> назад</a>, либо перейти <a href="/">На главную</a>
</div>
</body>
</html>