<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="author" content="merk">
    <link rel="stylesheet" href="/assets/css/bootstrap.min.css">
    <title>400 - Bad Request</title>
</head>
<body>
<div class="container" style="margin: auto">
    <div class="mt-1">
        <h1 class="text-warning">400 - Bad Request</h1>
    </div>
	<p class="lead">В запросе обнаружена синтаксическая ошибка.</p>
	Вы можете вернуться
	<a onclick="history.back(-1)" href="#"> назад</a>, либо перейти <a href="/">На главную</a>

</div>
</body>
</html>