<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="author" content="merk">
    <link rel="stylesheet" href="/assets/css/bootstrap.min.css">
    <title>500 - Internal Server Error</title>
</head>
<body>
<div class="container" style="margin: auto">
    <div class="mt-1">
        <h1 class="text-warning">500 - Internal Server Error</h1>
    </div>
    <p class="lead">Внутренняя ошибка сервера.</p>
    Мы уже в курсе проблемы и ведем работу по устранению неполадок.

</div>
</body>
</html>